<?php
/**
 *
 * @file cgd_cdi.module
 *   Contains cgd_cdi functionality.
 */

/**
 * Implements hook_menu().
 */
function cgd_cdi_menu() {
    $items = array();
    $items['commitment-development-index-2016'] = array(
        'page callback' => 'cgd_cdi_index_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['cdi-2016/country/%'] = array(
        'page callback' => 'cgd_cdi_country_page',
        'page arguments' => array(2),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
  
    return $items;
}

/**
 * Implements hook_theme().
 */
function cgd_cdi_theme() {
  return array(
    'cgd_cdi_index' => array(
      'template' => 'cgd_cdi_index',
    ),
    'cgd_cdi_country' => array(
      'variables' => array('countries' => NULL, 'indicators' => NULL),
      'template' => 'cgd_cdi_country',
    ),
    'cgd_cdi_footer' => array(
      'template' => 'cgd_cdi_footer',
    ),
  );
}

/*
 * module had been using drupal_add_html_head to add metatags to the head but many of those metatags already existed
 * using hook_html_head_alter instead (once for both index and country pages)
 */

/*
 * Implements hook_html_head_alter
 */

function cgd_cdi_html_head_alter(&$head_elements) {
  $cdiDescription = 'The Commitment to Development Index ranks 27 of the world’s richest countries on their dedication to policies that benefit people living in poorer nations. Denmark, Sweden, and Finland take first place in a three-way tie. The UK is tied for sixth while the United States is tied for 20th.';
  $cdiImageURL = 'http://www.cgdev.org/sites/default/files/cdi-2016-image-share_r.png'; 
  $head_elements['metatag_description_0']['#value'] = $cdiDescription;
  $head_elements['metatag_twitter:card_0']['#value'] = 'summary_large_image';
  $head_elements['metatag_twitter:title_0']['#value'] = 'Commitment to Development Index';
  $head_elements['metatag_twitter:image:src_0']['#value'] = $cdiImageURL;
  $head_elements['metatag_og:image_0'] = array(
    '#theme' => 'metatag_property',
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#id' => 'metatag_og:image_0',
    '#name' => 'og:image',
    '#value' => $cdiImageURL,
    '#weight' => 30,
    );
}

/**
 * Gets the content of the Country page.
 *
 * @return {string}
 *   The page content.
 */
function cgd_cdi_index_page() {
  drupal_add_css(drupal_get_path('module', 'cgd_cdi') . '/css/cgd_cdi.css');
  drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min.js', 'external');
  drupal_add_js('//connect.facebook.net/en_US/all.js', 'external');
  drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/backbone.js/0.9.2/backbone-min.js', 'external');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/cdi_app.combined.js');
  drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js', 'external');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/cgd_cdi_modal.combined.js');
  drupal_add_js(array('cgd_cdi' => array('pathToModule' => drupal_get_path('module', 'cgd_cdi'))), 'setting');

  drupal_set_title(t('Commitment to Development Index 2016')); 
  
  return theme('cgd_cdi_index') . theme('cgd_cdi_footer');
}

/**
 * Gets the content of the Country page.
 *
 * @return {string}
 *   The page content.
 */
function cgd_cdi_country_page($country_code) {
  $country = cgd_cdi_get_country_node($country_code);
  drupal_add_css(drupal_get_path('module', 'cgd_cdi') . '/css/cgd_cdi.css');
  drupal_add_js('countryCodes = ["' . $country_code. '"];', 'inline');
  drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min.js', 'external');
  drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/backbone.js/0.9.2/backbone-min.js', 'external');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/cdi_app.combined.js');
  drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js', 'external');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/cgd_cdi_modal.combined.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/cgd_cdi_country.js');
  drupal_add_js(array('cgd_cdi' => array('pathToModule' => drupal_get_path('module', 'cgd_cdi'))), 'setting');

  drupal_set_title(t('Commitment to Development Index 2016 - ' . $country->title));
  
  /*
  $content = node_view($country, 'teaser');
  $description_overall = strip_tags(drupal_render($content['field_overall']));
  
  $fbDescription = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'property' => 'og:description',
       'content' => $description_overall,
    ),
  );
  drupal_add_html_head($fbDescription, 'facebook_meta_description');


  $fbImage = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'property' => 'og:image',
       'content' => 'http://www.cgdev.org/sites/default/files/cdi-2016-image-share_r.png',
    ),
  );
  drupal_add_html_head($fbImage, 'facebook_meta_image');

   $twitterCard = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:card',
       'content' => 'summary_large_image',
    ),
  );
  drupal_add_html_head($twitterCard, 'twitter_meta_card');
  
   $twitterImage = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:image',
       'content' => 'http://www.cgdev.org/sites/default/files/cdi-2016-image-share_r.png',
    ),
  );
  drupal_add_html_head($twitterImage, 'twitter_meta_image');
  
    
  $twitterCreator = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:creator',
       'content' => '@cgdev',
    ),
  );
  drupal_add_html_head($twitterCreator, 'twitter_meta_creator');
  
      
  $twitterDescription = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:description',
       'content' => $description_overall,
    ),
  );
  drupal_add_html_head($twitterDescription, 'twitter_meta_description');
  
        
  $twitterTitle = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:title',
       'content' => 'The Commitment to Development Index',
    ),
  );
  drupal_add_html_head($twitterTitle, 'twitter_meta_title');
*/
  $indicators = array(
    'cdi' => 'field_overall',
    'cdi_aid' => 'field_aid',
    'cdi_inv' => 'field_finance',
    'cdi_tec' => 'field_technology',
    'cdi_env' => 'field_environment',
    'cdi_tra' => 'field_trade',
    'cdi_sec' => 'field_security',
    'cdi_mig' => 'field_migration',
  );

  $args = array(
    'countries' => array($country),
    'indicators' => $indicators,
  );

  return theme('cgd_cdi_country', $args) . theme('cgd_cdi_footer');
}

function cgd_cdi_get_country_node($country_code) {
  $result = db_query("SELECT c.entity_id 
    FROM field_data_field_country_code c
    WHERE c.entity_type = 'taxonomy_term' AND
    c.field_country_code_value = :country_code", array(':country_code' => $country_code));
  foreach ($result as $record) {
    $tid = $record->entity_id;
  }
  if (empty($tid)) {
    print 'Data not available.';
    return;
  }
  $nids = taxonomy_select_nodes($tid);
  $node = node_load($nids[0]);
  $node->country_code = $country_code;
    
  return $node;
}
