<?php
/**
 *
 * @file cgd_cdi.module
 *   Contains cgd_cdi functionality.
 */

/**
 * Implements hook_menu().
 */
function cgd_cdi_menu() {
    $items = array();
    $items['commitment-development-index-2016'] = array(
        'page callback' => 'cgd_cdi_index_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['cdi-2016/country/%'] = array(
        'page callback' => 'cgd_cdi_country_page',
        'page arguments' => array(2),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
  
    return $items;
}

/**
 * Implements hook_theme().
 */
function cgd_cdi_theme() {
  return array(
    'cgd_cdi_index' => array(
      'template' => 'cgd_cdi_index',
    ),
    'cgd_cdi_country' => array(
      'variables' => array('countries' => NULL, 'indicators' => NULL),
      'template' => 'cgd_cdi_country',
    ),
    'cgd_cdi_footer' => array(
      'template' => 'cgd_cdi_footer',
    ),
  );
}

/**
 * Gets the content of the Country page.
 *
 * @return {string}
 *   The page content.
 */
function cgd_cdi_index_page() {
  drupal_add_css(drupal_get_path('module', 'cgd_cdi') . '/css/cgd_cdi.css');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/underscore-1.3.3.min.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/backbone-0.9.2.min.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/bar-chart.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/cdi_app.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/home.cdi.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/home.cdi_indicators.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/home.cdi_components.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/line_chart.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/chart.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/cgd_cdi.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/cgd_cdi.modal.js');
  drupal_add_js(array('cgd_cdi' => array('pathToModule' => drupal_get_path('module', 'cgd_cdi'))), 'setting');

  drupal_set_title(t('Commitment to Development Index 2016'));
  
  $fbDescription = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'property' => 'og:description',
       'content' => 'The Commitment to Development Index ranks 27 of the richest countries on their dedication to policies that benefit poorer nations. Denmark takes first in 2016. The UK is tied for sixth while the United States is 21st. Japan takes last of 27.',
    ),
  );
  drupal_add_html_head($fbDescription, 'facebook_meta_description');

  $fbImage = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'property' => 'og:image',
       'content' => 'http://www.cgdev.org/sites/default/files/cdi-image-share.jpeg',
    ),
  );
  drupal_add_html_head($fbImage, 'facebook_meta_image');
  
  $twitterImage = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:image',
       'content' => 'http://www.cgdev.org/sites/default/files/cdi-2016.jpg',
    ),
  );
  drupal_add_html_head($twitterImage, 'twitter_meta_image');
  
    
  $twitterCreator = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:creator',
       'content' => '@cgdev',
    ),
  );
  drupal_add_html_head($twitterCreator, 'twitter_meta_creator');
  
      
  $twitterDescription = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:description',
       'content' => 'The Commitment to Development Index ranks 27 of the richest countries on their dedication to policies that benefit poorer nations. Denmark takes first in 2016. The UK is tied for sixth while the United States is 21st. Japan takes last of 27.',
    ),
  );
  drupal_add_html_head($twitterDescription, 'twitter_meta_description');
  
        
  $twitterTitle = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:title',
       'content' => 'The Commitment to Development Index',
    ),
  );
  drupal_add_html_head($twitterTitle, 'twitter_meta_title');
  
  return theme('cgd_cdi_index') . theme('cgd_cdi_footer');
}

/**
 * Gets the content of the Country page.
 *
 * @return {string}
 *   The page content.
 */
function cgd_cdi_country_page($country_code) {
  $country = cgd_cdi_get_country_node($country_code);
  drupal_add_css(drupal_get_path('module', 'cgd_cdi') . '/css/cgd_cdi.css');
  drupal_add_js('countryCodes = ["' . $country_code. '"];', 'inline');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/underscore-1.3.3.min.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/backbone-0.9.2.min.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/bar-chart.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/cdi_app.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/line_chart.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/chart.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/cgd_cdi.modal.js');
  drupal_add_js(drupal_get_path('module', 'cgd_cdi') . '/js/cgd_cdi_country.js');
  drupal_add_js(array('cgd_cdi' => array('pathToModule' => drupal_get_path('module', 'cgd_cdi'))), 'setting');

  drupal_set_title(t('Commitment to Development Index - ' . $country->title));
  
  
  $content = node_view($country, 'teaser');
  $description_overall = strip_tags(drupal_render($content['field_overall']));
  
  $fbDescription = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'property' => 'og:description',
       'content' => $description_overall,
    ),
  );
  drupal_add_html_head($fbDescription, 'facebook_meta_description');

  $fbImage = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'property' => 'og:image',
       'content' => 'http://www.cgdev.org/sites/default/files/cdi-2015.jpg',
    ),
  );
  drupal_add_html_head($fbImage, 'facebook_meta_image');
  
   $twitterImage = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:image',
       'content' => 'http://www.cgdev.org/sites/default/files/cdi-2015.jpg',
    ),
  );
  drupal_add_html_head($twitterImage, 'twitter_meta_image');
  
    
  $twitterCreator = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:creator',
       'content' => '@cgdev',
    ),
  );
  drupal_add_html_head($twitterCreator, 'twitter_meta_creator');
  
      
  $twitterDescription = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:description',
       'content' => $description_overall,
    ),
  );
  drupal_add_html_head($twitterDescription, 'twitter_meta_description');
  
        
  $twitterTitle = array(
    '#tag' => 'meta',
    '#attributes' => array(
       'name' => 'twitter:title',
       'content' => 'The Commitment to Development Index',
    ),
  );
  drupal_add_html_head($twitterTitle, 'twitter_meta_title');

  $indicators = array(
    'cdi' => 'field_overall',
    'cdi_aid' => 'field_aid',
    'cdi_inv' => 'field_finance',
    'cdi_tec' => 'field_technology',
    'cdi_env' => 'field_environment',
    'cdi_tra' => 'field_trade',
    'cdi_sec' => 'field_security',
    'cdi_mig' => 'field_migration',
  );

  $args = array(
    'countries' => array($country),
    'indicators' => $indicators,
  );

  return theme('cgd_cdi_country', $args) . theme('cgd_cdi_footer');
}

function cgd_cdi_get_country_node($country_code) {
  $result = db_query("SELECT c.entity_id 
    FROM field_data_field_country_code c
    WHERE c.entity_type = 'taxonomy_term' AND
    c.field_country_code_value = :country_code", array(':country_code' => $country_code));
  foreach ($result as $record) {
    $tid = $record->entity_id;
  }
  if (empty($tid)) {
    print 'Data not available.';
    return;
  }
  $nids = taxonomy_select_nodes($tid);
  $node = node_load($nids[0]);
  $node->country_code = $country_code;
    
  return $node;
}
